language: generic
sudo: true
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -qq -o Dpkg::Options::="--force-confnew" install docker-ce
jobs:
  include:
    - stage: auth, build, push
        - docker login -e="DH_EMAIL" -u="$DH_USER" -p="$DH_PASS"
        - docker build -f Dockerfile -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
        - docker push $REPO
      if: (branch = master) OR (tag IS present)
